apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
  ports:
    - port: 3000