stages:
  - build
  - lint
  - security
  - deploy

variables:
  DOCKER_IMAGE_NAME: "tuan1234/juice-shop"
  JUICE_SHOP_REMOTE_REPO_URL: "https://github.com/juice-shop/juice-shop.git"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  GIT_SUBMODULE_STRATEGY: recursive

build_docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - apk add git
    - cd juice-shop
    - docker build --cache-from $DOCKER_IMAGE_NAME -t $DOCKER_IMAGE_NAME:$CI_COMMIT_SHA . 
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE_NAME:$CI_COMMIT_SHA

tflint:
  stage: lint
  allow_failure: true
  image:
    name: ghcr.io/terraform-linters/tflint
  script:
    - tflint --chdir terraform

checkov:
  stage: lint
  allow_failure: true
  image:
    name: bridgecrew/checkov:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - checkov -d . -o junitxml | tee checkov.report.xml
  artifacts:
    reports:
      junit: "checkov.report.xml"
    paths:
      - "checkov.report.xml"

terrascan:
  stage: lint
  allow_failure: true
  image:
    name: tenable/terrascan:latest
    entrypoint: [ '/bin/sh', '-c' ]
  script:
    - /go/bin/terrascan scan .

terraform-fmt:
  stage: lint
  allow_failure: true
  image:
    name: hashicorp/terraform
  script:
    - terraform fmt -check

sonarqube:
  stage: lint
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - sonar-scanner -Dsonar.login=$SONARQUBE_LOGIN

owasp_zap_scan:
  stage: security
  image: owasp/zap2docker-stable:2.12.0
  allow_failure: true
  artifacts:
    when: always
    expire_in: "30 days"
    paths:
      - "owasp_zap_scan/testreport.xml"
  script:
    - mkdir -p /zap/wrk owasp_zap_scan
    - /zap/zap-baseline.py -t https://owasp-juice-shop-demo-0d931ec9d675.herokuapp.com/ -g gen.conf -x $(pwd)/owasp_zap_scan/testreport.xml

trivy:
  stage: security
  image:
    name: docker.io/aquasec/trivy:latest
    entrypoint: [""]
  variables:
    TRIVY_USERNAME: "$CI_REGISTRY_USER"
    TRIVY_PASSWORD: "$CI_REGISTRY_PASSWORD"
    TRIVY_AUTH_URL: "$CI_REGISTRY"
    TRIVY_CACHE_DIR: ".trivycache/"
  script:
    - docker pull "$DOCKER_IMAGE_NAME:$CI_COMMIT_SHA"
    - time trivy image --clear-cache
    - time trivy image --download-db-only
    - time trivy image --exit-code 0 --format template --template "@/contrib/gitlab.tpl" --output "$CI_PROJECT_DIR/trivy-report.json" "$DOCKER_IMAGE_NAME"
    - time trivy image --exit-code 0 "$DOCKER_IMAGE_NAME"
    - time trivy image --exit-code 1 --severity CRITICAL "$DOCKER_IMAGE_NAME"
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    expire_in: "1 week"
    paths:
      - trivy-report.json
  tags:
    - docker-runner

push_docker:
  stage: deploy
  image: docker:latest
  needs: ["build_docker"]
  services:
    - docker:dind
  script:
    - docker pull $DOCKER_IMAGE_NAME:$CI_COMMIT_SHA
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASWORD $CI_REGISTRY
    - docker tag $DOCKER_IMAGE_NAME:$CI_COMMIT_SHA $DOCKER_IMAGE_NAME:latest
    - docker push $DOCKER_IMAGE_NAME:latest
